# This is a basic workflow that is manually triggered

name: Release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version-number:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version number tag'
        # Default value if no value is explicitly provided
        default: 'Enter version number'
        # Input has to be provided for the workflow to run
        required: true
      release-name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Rlease name'
        # Default value if no value is explicitly provided
        default: 'Enter the release name'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version-number }}
          release_name: Release ${{ github.event.inputs.release-name }}
          body: |
            Changes in this Release
            - First Change:
            - Second Change:
          draft: false
          prerelease: false


